// <auto-generated />
using System;
using MANAGEMENT.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

namespace MANAGEMENTDLL.Migrations
{
    [DbContext(typeof(mgtDBContext))]
    partial class mgtDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("MANAGEMENTDLL.Models.AGRIDEP", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("AGRIDIRId");

                    b.Property<DateTime>("CREATION_DATE");

                    b.Property<decimal>("GOVId");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("NOTE")
                        .HasMaxLength(300);

                    b.Property<string>("ORDER")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<decimal>("USERNB");

                    b.HasKey("Id");

                    b.HasIndex("AGRIDIRId");

                    b.HasIndex("GOVId");

                    b.ToTable("AGRIDEP");
                });

            modelBuilder.Entity("MANAGEMENTDLL.Models.AGRIDIR", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CREATION_DATE");

                    b.Property<decimal>("GOVId");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("NOTE")
                        .HasMaxLength(300);

                    b.Property<string>("ORDER")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<decimal>("USERNB");

                    b.HasKey("Id");

                    b.HasIndex("GOVId");

                    b.ToTable("AGRIDIR");
                });

            modelBuilder.Entity("MANAGEMENTDLL.Models.AGRISEC", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("AGRIDEPId");

                    b.Property<decimal>("AGRIDIRId");

                    b.Property<DateTime>("CREATION_DATE");

                    b.Property<decimal>("GOVId");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("NOTE")
                        .HasMaxLength(300);

                    b.Property<string>("ORDER")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<decimal>("SIDEId");

                    b.Property<decimal>("USERNB");

                    b.Property<decimal>("ZONEId");

                    b.HasKey("Id");

                    b.HasIndex("AGRIDEPId");

                    b.HasIndex("AGRIDIRId");

                    b.HasIndex("GOVId");

                    b.HasIndex("SIDEId");

                    b.HasIndex("ZONEId");

                    b.ToTable("AGRISEC");
                });

            modelBuilder.Entity("MANAGEMENTDLL.Models.AREA", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CREATION_DATE");

                    b.Property<decimal>("GOVId");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("NOTE")
                        .HasMaxLength(300);

                    b.Property<string>("ORDER")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<decimal>("USERNB");

                    b.HasKey("Id");

                    b.HasIndex("GOVId");

                    b.ToTable("AREA");
                });

            modelBuilder.Entity("MANAGEMENTDLL.Models.BRANCH", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CREATION_DATE");

                    b.Property<decimal>("GOVId");

                    b.Property<string>("HEADNAME")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("NOTE")
                        .HasMaxLength(300);

                    b.Property<string>("ORDER")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<decimal>("USERNB");

                    b.HasKey("Id");

                    b.HasIndex("GOVId");

                    b.ToTable("BRANCH");
                });

            modelBuilder.Entity("MANAGEMENTDLL.Models.CIRCLE", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("BRANCHId");

                    b.Property<DateTime>("CREATION_DATE");

                    b.Property<decimal>("GOVId");

                    b.Property<string>("HEADNAME")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("NOTE")
                        .HasMaxLength(300);

                    b.Property<string>("ORDER")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<decimal>("USERNB");

                    b.HasKey("Id");

                    b.HasIndex("BRANCHId");

                    b.HasIndex("GOVId");

                    b.ToTable("CIRCLE");
                });

            modelBuilder.Entity("MANAGEMENTDLL.Models.GOVERNORATE", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CREATION_DATE");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("NOTE")
                        .HasMaxLength(300);

                    b.Property<string>("ORDER")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<decimal>("USERNB");

                    b.HasKey("Id");

                    b.ToTable("GOVERNORATE");
                });

            modelBuilder.Entity("MANAGEMENTDLL.Models.INDIC", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("AGRISECId");

                    b.Property<DateTime>("CREATION_DATE");

                    b.Property<decimal>("GOVId");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("NOTE")
                        .HasMaxLength(300);

                    b.Property<string>("ORDER")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<decimal>("SIDEId");

                    b.Property<decimal>("USERNB");

                    b.Property<decimal>("VILId");

                    b.Property<decimal>("ZONEId");

                    b.HasKey("Id");

                    b.HasIndex("AGRISECId");

                    b.HasIndex("GOVId");

                    b.HasIndex("SIDEId");

                    b.HasIndex("VILId");

                    b.HasIndex("ZONEId");

                    b.ToTable("INDIC");
                });

            modelBuilder.Entity("MANAGEMENTDLL.Models.SECTION", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("BRANCHId");

                    b.Property<decimal>("CIRCLEId");

                    b.Property<DateTime>("CREATION_DATE");

                    b.Property<decimal>("GOVId");

                    b.Property<string>("HEADNAME")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("NOTE")
                        .HasMaxLength(300);

                    b.Property<string>("ORDER")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<decimal>("USERNB");

                    b.HasKey("Id");

                    b.HasIndex("BRANCHId");

                    b.HasIndex("CIRCLEId");

                    b.HasIndex("GOVId");

                    b.ToTable("SECTION");
                });

            modelBuilder.Entity("MANAGEMENTDLL.Models.SIDE", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CREATION_DATE");

                    b.Property<decimal>("GOVId");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("NOTE")
                        .HasMaxLength(300);

                    b.Property<string>("ORDER")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<decimal>("USERNB");

                    b.Property<decimal>("ZONEId");

                    b.HasKey("Id");

                    b.HasIndex("GOVId");

                    b.HasIndex("ZONEId");

                    b.ToTable("SIDE");
                });

            modelBuilder.Entity("MANAGEMENTDLL.Models.VILLAGE", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CREATION_DATE");

                    b.Property<decimal>("GOVId");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("NOTE")
                        .HasMaxLength(300);

                    b.Property<string>("ORDER")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<decimal>("SIDEId");

                    b.Property<decimal>("USERNB");

                    b.Property<decimal>("ZONEId");

                    b.HasKey("Id");

                    b.HasIndex("GOVId");

                    b.HasIndex("SIDEId");

                    b.HasIndex("ZONEId");

                    b.ToTable("VILLAGE");
                });

            modelBuilder.Entity("MANAGEMENTDLL.Models.ZONE", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CREATION_DATE");

                    b.Property<decimal>("GOVId");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("NOTE")
                        .HasMaxLength(300);

                    b.Property<string>("ORDER")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<decimal>("USERNB");

                    b.HasKey("Id");

                    b.HasIndex("GOVId");

                    b.ToTable("ZONE");
                });

            modelBuilder.Entity("MANAGEMENTDLL.Models.AGRIDEP", b =>
                {
                    b.HasOne("MANAGEMENTDLL.Models.AGRIDIR", "AGRIDIR")
                        .WithMany("AGRIDEP")
                        .HasForeignKey("AGRIDIRId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MANAGEMENTDLL.Models.GOVERNORATE", "GOVERNORATE")
                        .WithMany()
                        .HasForeignKey("GOVId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MANAGEMENTDLL.Models.AGRIDIR", b =>
                {
                    b.HasOne("MANAGEMENTDLL.Models.GOVERNORATE", "GOVERNORATE")
                        .WithMany()
                        .HasForeignKey("GOVId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MANAGEMENTDLL.Models.AGRISEC", b =>
                {
                    b.HasOne("MANAGEMENTDLL.Models.AGRIDEP", "AGRIDEP")
                        .WithMany("AGRISEC")
                        .HasForeignKey("AGRIDEPId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MANAGEMENTDLL.Models.AGRIDIR", "AGRIDIR")
                        .WithMany()
                        .HasForeignKey("AGRIDIRId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MANAGEMENTDLL.Models.GOVERNORATE", "GOVERNORATE")
                        .WithMany()
                        .HasForeignKey("GOVId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MANAGEMENTDLL.Models.SIDE", "SIDE")
                        .WithMany()
                        .HasForeignKey("SIDEId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MANAGEMENTDLL.Models.ZONE", "ZONE")
                        .WithMany()
                        .HasForeignKey("ZONEId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MANAGEMENTDLL.Models.AREA", b =>
                {
                    b.HasOne("MANAGEMENTDLL.Models.GOVERNORATE", "GOVERNORATE")
                        .WithMany()
                        .HasForeignKey("GOVId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MANAGEMENTDLL.Models.BRANCH", b =>
                {
                    b.HasOne("MANAGEMENTDLL.Models.GOVERNORATE", "GOVERNORATE")
                        .WithMany("BRANCH")
                        .HasForeignKey("GOVId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MANAGEMENTDLL.Models.CIRCLE", b =>
                {
                    b.HasOne("MANAGEMENTDLL.Models.BRANCH", "BRANCH")
                        .WithMany("CIRCLE")
                        .HasForeignKey("BRANCHId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MANAGEMENTDLL.Models.GOVERNORATE", "GOVERNORATE")
                        .WithMany()
                        .HasForeignKey("GOVId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MANAGEMENTDLL.Models.INDIC", b =>
                {
                    b.HasOne("MANAGEMENTDLL.Models.AGRISEC", "AGRISEC")
                        .WithMany()
                        .HasForeignKey("AGRISECId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MANAGEMENTDLL.Models.GOVERNORATE", "GOVERNORATE")
                        .WithMany()
                        .HasForeignKey("GOVId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MANAGEMENTDLL.Models.SIDE", "SIDE")
                        .WithMany()
                        .HasForeignKey("SIDEId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MANAGEMENTDLL.Models.VILLAGE", "VILLAGE")
                        .WithMany()
                        .HasForeignKey("VILId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MANAGEMENTDLL.Models.ZONE", "ZONE")
                        .WithMany()
                        .HasForeignKey("ZONEId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MANAGEMENTDLL.Models.SECTION", b =>
                {
                    b.HasOne("MANAGEMENTDLL.Models.BRANCH", "BRANCH")
                        .WithMany()
                        .HasForeignKey("BRANCHId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MANAGEMENTDLL.Models.CIRCLE", "CIRCLE")
                        .WithMany()
                        .HasForeignKey("CIRCLEId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MANAGEMENTDLL.Models.GOVERNORATE", "GOVERNORATE")
                        .WithMany()
                        .HasForeignKey("GOVId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MANAGEMENTDLL.Models.SIDE", b =>
                {
                    b.HasOne("MANAGEMENTDLL.Models.GOVERNORATE", "GOVERNORATE")
                        .WithMany()
                        .HasForeignKey("GOVId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MANAGEMENTDLL.Models.ZONE", "ZONE")
                        .WithMany("SIDE")
                        .HasForeignKey("ZONEId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MANAGEMENTDLL.Models.VILLAGE", b =>
                {
                    b.HasOne("MANAGEMENTDLL.Models.GOVERNORATE", "GOVERNORATE")
                        .WithMany()
                        .HasForeignKey("GOVId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MANAGEMENTDLL.Models.SIDE", "SIDE")
                        .WithMany("VILLAGE")
                        .HasForeignKey("SIDEId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MANAGEMENTDLL.Models.ZONE", "ZONE")
                        .WithMany()
                        .HasForeignKey("ZONEId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MANAGEMENTDLL.Models.ZONE", b =>
                {
                    b.HasOne("MANAGEMENTDLL.Models.GOVERNORATE", "GOVERNORATE")
                        .WithMany("ZONE")
                        .HasForeignKey("GOVId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
